name: Commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip

      - name: Install dependencies
        run: python -m pip install -e .[test]

      - name: Run tests
        run: python -m coverage run -m pytest

      - name: Create coverage report
        run: python -m coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v5
        with:
          name: Coverage report
          path: htmlcov/

  type_check:
    name: Check types

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip

      - name: Install dependencies
        run: python -m pip install -e .[test]

      - name: Check with Pyright
        uses: jakebailey/pyright-action@v2

  nix_check:
    name: Check Nix flake

    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: danth
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check Nix flake
        run: nix flake check github:${{ github.repository }}/${{ github.sha }}

  release:
    name: Release

    needs: [ test, type_check, nix_check ]

    if: github.repository_owner == 'danth' && github.ref_name == 'master'

    concurrency:
      group: release
      cancel-in-progress: false

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Reset to ${{ github.sha }}
        run: git reset --hard ${{ github.sha }}

      - name: Create release
        id: release
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: github-actions
          git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          changelog: false

    outputs:
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}

  build:
    name: Build

    needs: [ release ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ needs.release.outputs.tag }}

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip

      - name: Install dependencies
        run: python -m pip install -e .[build]

      - name: Build package
        run: python -m build .

      - name: Upload build artifacts
        id: artifact
        uses: actions/upload-artifact@v5
        with:
          name: Build artifacts
          path: dist/

    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}

  publish:
    name: Publish

    needs: [ build, release ]

    if: needs.release.outputs.released == 'true'

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v6
        with:
          artifact-ids: ${{ needs.build.outputs.artifact-id }}
          path: dist/

      - name: Upload build artifacts
        uses: python-semantic-release/publish-action@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.release.outputs.tag }}

