name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release

    if: github.repository_owner == 'danth'

    concurrency:
      group: release-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Reset to ${{ github.sha }}
        run: git reset --hard ${{ github.sha }}

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip

      - name: Install dependencies
        run: python -m pip install -e .[build,test]

      - name: Check with Pyright
        uses: jakebailey/pyright-action@v2

      - name: Check with Pytest
        run: python -m pytest

      - name: Create release
        id: release
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: github-actions
          git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          changelog: false

      - name: Build artifacts
        run: python -m build .

      - name: Upload release
        if: steps.release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
